### ISSUE TITLE
Autobuy corpse -something is bugged

### ISSUE THREAD

**Issue by Sk4jz** [tollofsen/uzi#10]
Welcome to the land of Burning! May your visit here be... Interesting.
The Temple of Karandras
cast 'HASTE'
Obvious exits: [North, East, South, West]
A huge altar made of polished white marble carries an important message. [2]
A bulletin board for important player INFORMATION.
Bragger the Half-Orc is standing here.
Kasumi the K'ta'viir is standing here.
Monokora the K'ta'viir is standing here.
Knurks the K'ta'viir (invisible) (not playing) is standing here.
Grymling the K'ta'viir (invisible) (not playing) is standing here.
Baracus the K'ta'viir (invisible) (sanctuary) (not playing) is here circling around in the air.
Magamedov the Elf (invisible) (sanctuary) (not playing) is standing here.
Tiberius the Dwarf (sanctuary) (not playing) is standing here.
You carry no coins and your balance is 2,754,019,360 coins.
---------- Greenknight ----------
------ Affecting Spells ------
Darkvision              Permanent.
The Fountain Square of Karandras
Obvious exits: [North, East, South, West]
A beautiful fountain stands here, spraying clear water.
Girle the K'ta'viir is here circling around in the air.
Drutten the K'ta'viir is standing here.
Facebook the Human is here circling around in the air.
Tyrell the Drow is standing here.
Koschei the Drow (invisible) is here circling around in the air.
A large white swan flaps it's wings and honks.
Chief Ramu the K'ta'viir (hidden) is standing here.
An explorer from a distant land gathers his thoughts on the city here.
Rufio the Troll (invisible) is here circling around in the air.
Triad the Half-Orc is standing here.
Venathor the K'ta'viir (sanctuary) (not playing) is standing here.
Versatile the K'ta'viir is here circling around in the air.
Laazar the K'ta'viir is standing here.
Urkel the K'ta'viir is standing here.
Wallie the K'ta'viir (invisible) is standing here.
Jagularen the K'ta'viir is standing here.
Turia the K'ta'viir is standing here.
Stinch the K'ta'viir (invisible) (sanctuary) is standing here.
Guano the K'ta'viir is here circling around in the air.
Aeron the Half-Orc (invisible) is here circling around in the air.
Temple street

TinyFugue version 5.0 beta 8
Copyright (C) 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2002, 2003, 2004, 2005, 2006-2007 Ken Keys (kenkeys@users.sourceforge.net)
Type `/help copyright' for more information.
Using PCRE version 8.35 2014-04-04
Type`/help', `/help topics', or`/help intro' for help.
Type `/quit' to quit tf.

% LC_CTYPE category set to "en_US.UTF-8" locale.
% LC_TIME category set to "en_US.UTF-8" locale.
% Loading commands from /usr/share/tf5/tf-lib/stdlib.tf.
% Loading commands from /home/mange/.tfrc.
% Loading commands from uzi/uzi.
% Loading commands from /usr/share/tf5/tf-lib/finger.tf.
% Loading commands from /usr/share/tf5/tf-lib/alias.tf.
% Loading commands from /usr/share/tf5/tf-lib/lisp.tf.
% Loading commands from /usr/share/tf5/tf-lib/tools.tf.
% Loading commands from /usr/share/tf5/tf-lib/lisp.tf.
% Current directory is /home/mange/uzi
% Current directory is /home/mange
% Loading commands from tiny.world.
% tiny.world, line 1: addworld: Warning: file contains passwords and is readable by others.
  38(1911)H 1187(1373)M 553(553)V >   tells(0) tank(Puck) damage(pb:1) weapon(parang) cop(on:0) [bm:0|ff:0|mi:0]                                                                                                                 time(22:21)
/menu

TinyFugue version 5.0 beta 8
Copyright (C) 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2002, 2003, 2004, 2005, 2006-2007 Ken Keys (kenkeys@users.sourceforge.net)
Type `/help copyright' for more information.
Using PCRE version 8.35 2014-04-04
Type`/help', `/help topics', or`/help intro' for help.
Type `/quit' to quit tf.

% LC_CTYPE category set to "en_US.UTF-8" locale.
% LC_TIME category set to "en_US.UTF-8" locale.
% Loading commands from /usr/share/tf5/tf-lib/stdlib.tf.
% Loading commands from /home/mange/.tfrc.
% Loading commands from uzi/uzi.
% Loading commands from /usr/share/tf5/tf-lib/finger.tf.
% Loading commands from /usr/share/tf5/tf-lib/alias.tf.
% Loading commands from /usr/share/tf5/tf-lib/lisp.tf.
% Loading commands from /usr/share/tf5/tf-lib/tools.tf.
% Loading commands from /usr/share/tf5/tf-lib/lisp.tf.
% Current directory is /home/mange/uzi
% Current directory is /home/mange
Obvious exits: [North, East, South]
The swinging sign of 'The Trafford Arms' inn hangs above a door to the east.
Khold the K'ta'viir is standing here.
An senior citizen of Karandras is pottering about here.
An amiable citizen of the fair city of Karandras stands here.
A little duck waddles around here quacking as it goes.
Temple street
Obvious exits: [North, South, West]
A gold plaque is fastened beside the entry to the Adventurer's bureau to the west.
A weary traveller rests here, taking a break from his journey.
A pigeon is walking around here, nodding it's head as it goes.
Entrance to the Adventurer's Bureau
Obvious exits: [North, East, South, West]
An elite guard stands here, guarding his post.
...glowing with a bright light!
An elite guard stands here, guarding his post.
...glowing with a bright light!
An elite guard stands here, guarding his post.
...glowing with a bright light!
A hallway in the Adventurer's Bureau
Obvious exits: [North, East, South, West]
Karandras Corpse Retrieval Office
Obvious exits: [North, East, South]
A compass lies here [3]
A magical flask has been carelessly discarded here.
A blood-red stone shaped as a star lies here.
You see a parchment here with an incantation written on it.
A large key has been discarded here.
A Large device from the Lords of Orhan has been put here.
Sheila, the secretary for the CR office, is here to take your request.
Sheila says 'Sorry Greenknight, you don't have the 2009080 gold coins that we would have to charge for that corpse retrieval!'
Saving Greenknight.
You have to rent to toggle playing off.
Corpse Retrieval Waiting Room
Obvious exits: [North]
Ok.
cast 'FLY'
Suddenly the world starts to slow down.
Khold tells the The Trocade, 'idiotprallar som inte healar.'
There's no ATM here!
Sorry, but you cannot do that here!
cast 'FLY'
You lost your concentration!
[INFO] The Major Eraditor was savagely backstabbed to death by Charlemagne of Puck's group.
Ok.
cast 'CONTINGENCY'
You grow small black bat-wings and start flapping.
Ok.
You are protected from great harm!!!
Girle tells the The Trocade, 'myst..'
the green carriage driver yells 'Leaving for The Grand Gate of Thalos next!'
the yellow carriage driver yells 'Leaving for Plaza of Kerofk next!'
Khold tells the The Trocade, 'prallarnas fel'
You are carrying:
 Nothing.
Puck tells the The Trocade, 'alltid'
% Speedwalk disabled.
Corpse Retrieval Waiting Room
  You have entered the waiting room.  Fine chairs line the walls as you
see other adventurers waiting for the corpses to be retrieved.  Although
you are naked, you feel quite warm and peaceful in this room.  The Corpse
Retrieval office lies north.
Obvious exits: [North]
[The Trocade] Puck nods solemnly.
Puck gossips, 'safe to get back'

**Comment by tollofsen** [comment]
I've fixed it. I just haven't committed in a while. I'll push a fix for this and lots of other stuff this weekend. The "toggle play and walk south on reboot" feature broke the autocr functionality.

**Comment by tollofsen** [comment]
Fixed by commit 1453f1d72ea94c6a43bdf13332db267c99ec3207
