### ISSUE TITLE
Saker att lägga till :)

### ISSUE THREAD

**Issue by Sk4jz** [tollofsen/uzi#2]
buy corpse, på tell
att man byter till horgar vapen, även om autochange är av
gt status -lag till aholy on/off dar
bind / till group priest ;)
mer speedies ;)

**Comment by tollofsen** [comment]
Vad menas med horgar vapen punkten? Även om cweap är av? Inte ASC antar jag?

**Comment by tollofsen** [comment]
Split into multiple issues.

#3 Improve AutoCR to buy on tell
#4 Add additional speedwalks
#5 Display autoholy status in status tell for priest 
#6 Built in alias to list priests in group

**Comment by Sk4jz** [comment]
Menr att, när jag köra manamode, så har jag inte CWEAP på alls, vilket innebär att jag inte byter vapen på Horgars :)

Nu är ju en Athame inte så noga och tappa men :)
