### ISSUE TITLE
Built in alias to list priests in group

### ISSUE THREAD

**Issue by tollofsen** [tollofsen/uzi#6]
I personally use m as an alias for group priest. But I don't think theres a built in alias/binding in uzi. @Sk4jz suggested binding it to /. But, well thats somewhat cumbersome to type.

**Comment by Sk4jz** [comment]
In bind.m i suggest to change the following:
/def key_f2 = aff to /def key_f2 = group priest
and
/def key_nkp, = inv to /def key_nkp, = aff

Much more usefull binds :)

**Comment by tollofsen** [comment]
Solved by commit 4fd442568c16b4f092f042276c68f613ba91d6b9
